# Generated by Django 3.0.3 on 2020-03-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0012_auto_20200325_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghostpost',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
    ]
