# Generated by Django 3.0.3 on 2020-04-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0013_ghostpost_total_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghostpost',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='ghostpost',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='ghostpost',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
